version = 0.1

[default.deploy.parameters]
stack_name = "sam-fastapi-mangum"
resolve_s3 = true
s3_prefix = "sam-fastapi-mangum"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
